sudo: required
language: node_js
node_js:
#  - stable
  - 10
  - 9
  - 8
#  - 6
#  - 4
#  - 0.12
#  - 0.11

services:
  - docker

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d
  - npm install sqlite3 --build-from-source

env:
  - TEST_DB=mariadb
  - TEST_DB=mongodb
  - TEST_DB=mssql
  - TEST_DB=mysql
  - TEST_DB=oracle
  - TEST_DB=postgres
  - TEST_DB=sqlite
  - TEST_DB=sqljs

script:
  - npm run lint
  - cp ormconfigs/ormconfig.$TEST_DB.json ormconfig.json
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
